site_name: Agile in Exile - Engineering Notes
site_url: https://blog.gleam.ch  
  
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - content.code.copy
  nav:
    - Home: index.md
    - PUML: puml.md
plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
